# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#PERMITIR CONEXIONES DESDE PROXY INVERSO
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.10